// Assets/Editor/AnimatorControllerCodeGenTool.cs
// 选中 AnimatorController 后：Assets/动画工具/生成代码
// 生成 DefAnimatorController_XXX.cs（XXX = Controller 名称）

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace Game.Editor
{
    public static class AnimatorControllerCodeGenTool
    {
        // 你指定的菜单路径（按你的要求保持一致）
        private const string MenuPath = "Assets/动画工具/生成代码";

        // 你指定的输出目录（用常量定义）
        // 相对工程根目录，必须以 Assets/ 开头
        private const string OutputDir = "Assets/Scripts/Game/Hot/Code/Runtime/3C/Defination/Gen/";

        // 生成文件放进这个命名空间（按需改）
        private const string OutputNamespace = "Game.Hot";

        [MenuItem(MenuPath, true)]
        private static bool ValidateGenerate()
        {
            return Selection.activeObject is AnimatorController;
        }

        [MenuItem(MenuPath, false, 2000)]
        private static void Generate()
        {
            var controller = Selection.activeObject as AnimatorController;
            if (controller == null)
            {
                Debug.LogError("[动画工具] 未选中 AnimatorController，已取消。");
                return;
            }

            EnsureOutputDir(OutputDir);

            string controllerName = controller.name;
            string fileName = $"DefAnimatorController_{controllerName}.cs";
            string filePath = Path.Combine(OutputDir, fileName).Replace("\\", "/");

            string className = SanitizeTypeName($"DefAnimatorController_{controllerName}");

            Debug.Log($"[动画工具] 开始生成：{fileName}");
            Debug.Log($"[动画工具] AnimatorController：{AssetDatabase.GetAssetPath(controller)}");
            Debug.Log($"[动画工具] 输出路径：{filePath}");

            var sb = new StringBuilder(16 * 1024);

            // 缩进控制
            const string IND0 = "";
            const string IND1 = "    ";
            const string IND2 = "        ";
            const string IND3 = "            ";
            const string IND4 = "                ";
            const string IND5 = "                    ";
            const string IND6 = "                        ";
            const string IND7 = "                            ";
            const string IND8 = "                                ";

            // 文件头
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by AnimatorControllerCodeGenTool.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();

            // namespace + 外层 class
            sb.AppendLine($"{IND0}namespace {OutputNamespace}");
            sb.AppendLine($"{IND0}{{");
            sb.AppendLine($"{IND1}public static class {className}");
            sb.AppendLine($"{IND1}{{");

            var layers = controller.layers ?? Array.Empty<AnimatorControllerLayer>();

            // ===== 生成顺序 1：Layers（注意：这里是 enum 名从 Layer -> Layers）=====
            sb.AppendLine($"{IND2}/// <summary>Animator Controller layers.</summary>");
            sb.AppendLine($"{IND2}public enum Layers");
            sb.AppendLine($"{IND2}{{");
            sb.AppendLine($"{IND3}None = -1,");

            for (int i = 0; i < layers.Length; i++)
            {
                string layerNameRaw = layers[i]?.name ?? $"Layer{i}";
                string layerEnumName = SanitizeEnumMember(layerNameRaw);
                sb.AppendLine($"{IND3}{layerEnumName} = {i},");
            }

            sb.AppendLine($"{IND2}}}");
            sb.AppendLine();

            // ===== 生成顺序 2：Params（Animator Controller 所有 Parameters）=====
            sb.AppendLine($"{IND2}/// <summary>Animator Controller parameters.</summary>");
            sb.AppendLine($"{IND2}public static class Params");
            sb.AppendLine($"{IND2}{{");

            var parameters = controller.parameters ?? Array.Empty<AnimatorControllerParameter>();
            if (parameters.Length == 0)
            {
                sb.AppendLine($"{IND3}// (no parameters found)");
            }
            else
            {
                var usedParamFieldNames = new HashSet<string>(StringComparer.Ordinal);
                int exportedParams = 0;

                foreach (var p in parameters)
                {
                    if (p == null || string.IsNullOrWhiteSpace(p.name))
                        continue;

                    string paramName = p.name;
                    string fieldNameBase = SanitizeConstFieldName(paramName);
                    string fieldName = MakeUnique(fieldNameBase, usedParamFieldNames);

                    sb.AppendLine($"{IND3}public const string {fieldName} = \"{EscapeForCSharpString(paramName)}\";");
                    exportedParams++;
                }

                if (exportedParams == 0)
                    sb.AppendLine($"{IND3}// (no parameters found)");
            }

            sb.AppendLine($"{IND2}}}");
            sb.AppendLine();

            // ===== 生成顺序 3：States（注意：类名从 State -> States）=====
            sb.AppendLine($"{IND2}/// <summary>All layer state name constants.</summary>");
            sb.AppendLine($"{IND2}public static class States");
            sb.AppendLine($"{IND2}{{");

            for (int i = 0; i < layers.Length; i++)
            {
                var layer = layers[i];
                if (layer == null)
                    continue;

                string layerNameRaw = string.IsNullOrWhiteSpace(layer.name) ? $"Layer{i}" : layer.name;
                string layerClassName = SanitizeTypeName(layerNameRaw);

                sb.AppendLine($"{IND3}/// <summary>Layer: {EscapeForXml(layerNameRaw)} (index {i})</summary>");
                sb.AppendLine($"{IND3}public static class {layerClassName}");
                sb.AppendLine($"{IND3}{{");

                var allStates = new List<AnimatorState>();
                CollectStatesRecursive(layer.stateMachine, allStates);

                // 去重：普通 state 字段名冲突时自动加 _2, _3...
                var usedStateFieldNames = new HashSet<string>(StringComparer.Ordinal);
                // BlendTree 分组 class 名：BlendTree_XXX（XXX=状态名），冲突时自动加 _2...
                var usedBlendTreeGroupNames = new HashSet<string>(StringComparer.Ordinal);

                int exportedStates = 0;

                foreach (var st in allStates)
                {
                    if (st == null || string.IsNullOrWhiteSpace(st.name))
                        continue;

                    string stateName = st.name;
                    var motion = st.motion;

                    // 基础字段名：用 State 名称做合法化/唯一化
                    string fieldNameBase = SanitizeConstFieldName(stateName);
                    string fieldName = MakeUnique(fieldNameBase, usedStateFieldNames);

                    if (motion == null)
                    {
                        sb.AppendLine(
                            $"{IND4}public static readonly (string stateName, string motionName) {fieldName} = " +
                            $"(\"{EscapeForCSharpString(stateName)}\", \"\");"
                        );
                        exportedStates++;
                        continue;
                    }

                    // ====== 关键修改：BlendTree 生成改为“无 Children 层，直接嵌套结构” ======
                    if (motion is BlendTree rootBt)
                    {
                        // class 名固定为 BlendTree_XXX（XXX=状态名）
                        string groupNameBase = SanitizeTypeName($"BT_{stateName}");
                        string groupName = MakeUnique(groupNameBase, usedBlendTreeGroupNames);

                        string rootBtName = TrimAnimExtension(rootBt.name ?? string.Empty);

                        sb.AppendLine($"{IND4}/// <summary>");
                        sb.AppendLine($"{IND4}/// State: {EscapeForXml(stateName)}");
                        sb.AppendLine($"{IND4}/// Root BlendTree: {EscapeForXml(string.IsNullOrEmpty(rootBtName) ? "(Unnamed BlendTree)" : rootBtName)}");
                        sb.AppendLine($"{IND4}/// Structure: Self + direct children (clips) + nested BlendTrees.");
                        sb.AppendLine($"{IND4}/// </summary>");
                        sb.AppendLine($"{IND4}public static class {groupName}");
                        sb.AppendLine($"{IND4}{{");

                        // 递归输出：在当前 class 内直接输出 Self + children（不再插 Children_xxx）
                        EmitBlendTreeBody(
                            sb,
                            indentMember: IND5,
                            indentInnerClass: IND5, // 子 class 的 public static class 也用同级缩进
                            stateName: stateName,
                            bt: rootBt,
                            btDisplayName: rootBtName,
                            exportedCount: ref exportedStates
                        );

                        sb.AppendLine($"{IND4}}}");
                        sb.AppendLine();

                        // 不额外生成 {fieldName}，避免同一 state 两套入口
                        continue;
                    }

                    // 普通 motion（Clip 等）
                    string motionNameNormal = TrimAnimExtension(motion.name ?? string.Empty);
                    sb.AppendLine(
                        $"{IND4}public static readonly (string stateName, string motionName) {fieldName} = " +
                        $"(\"{EscapeForCSharpString(stateName)}\", \"{EscapeForCSharpString(motionNameNormal)}\");"
                    );
                    exportedStates++;
                }

                if (exportedStates == 0)
                    sb.AppendLine($"{IND4}// (no states found)");

                sb.AppendLine($"{IND3}}}");
                sb.AppendLine();
            }

            sb.AppendLine($"{IND2}}}");
            sb.AppendLine();

            // 收尾：class + namespace
            sb.AppendLine($"{IND1}}}");
            sb.AppendLine($"{IND0}}}");

            // 写文件（存在则替换）
            try
            {
                File.WriteAllText(filePath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                Debug.Log($"[动画工具] 生成成功（已写入/替换）：{filePath}");
            }
            catch (Exception e)
            {
                Debug.LogError($"[动画工具] 写入失败：{filePath}\n{e}");
                return;
            }

            AssetDatabase.Refresh();
            Debug.Log("[动画工具] AssetDatabase.Refresh 完成。");
        }

        // ----------------------
        // Helpers
        // ----------------------

        private static void EnsureOutputDir(string dir)
        {
            if (AssetDatabase.IsValidFolder(dir))
                return;

            // 逐级创建
            string[] parts = dir.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 0 || parts[0] != "Assets")
                throw new Exception($"OutputDir 必须以 'Assets/' 开头：{dir}");

            string current = "Assets";
            for (int i = 1; i < parts.Length; i++)
            {
                string next = $"{current}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                    Debug.Log($"[动画工具] 创建目录：{next}");
                }
                current = next;
            }
        }

        private static void CollectStatesRecursive(AnimatorStateMachine sm, List<AnimatorState> outStates)
        {
            if (sm == null) return;

            // 当前状态机的 states
            var states = sm.states;
            for (int i = 0; i < states.Length; i++)
            {
                var st = states[i].state;
                if (st != null) outStates.Add(st);
            }

            // 子状态机递归
            var sub = sm.stateMachines;
            for (int i = 0; i < sub.Length; i++)
            {
                CollectStatesRecursive(sub[i].stateMachine, outStates);
            }
        }

        // ---- BlendTree：更短访问路径的嵌套生成（核心） ----
        //
        // 生成形态（每个 BlendTree class 内部）：
        // - Self
        // - (Clip 常量...)  // 直接在当前层
        // - BT_子BlendTree名  // 直接嵌套
        //   - Self
        //   - (Clip 常量...)
        //   - BT_孙BlendTree名 ...
        //
        // 这样就不需要：Children_xxx 这一层，访问路径会明显变短。
        private static void EmitBlendTreeBody(
            StringBuilder sb,
            string indentMember,
            string indentInnerClass,
            string stateName,
            BlendTree bt,
            string btDisplayName,
            ref int exportedCount
        )
        {
            // Self（当前 BlendTree 自己）
            sb.AppendLine(
                $"{indentMember}public static readonly (string stateName, string motionName) Self = " +
                $"(\"{EscapeForCSharpString(stateName)}\", \"{EscapeForCSharpString(btDisplayName ?? string.Empty)}\");"
            );
            exportedCount++;

            if (bt == null || bt.children == null || bt.children.Length == 0)
            {
                sb.AppendLine($"{indentMember}// (no children found in BlendTree)");
                return;
            }

            // 当前层去重：Clip 字段名、子 BlendTree class 名
            var usedClipFieldNames = new HashSet<string>(StringComparer.Ordinal);
            var usedBtTypeNames = new HashSet<string>(StringComparer.Ordinal);

            var children = bt.children;
            for (int i = 0; i < children.Length; i++)
            {
                var m = children[i].motion;
                if (m == null) continue;

                if (m is BlendTree childBt)
                {
                    string childBtName = TrimAnimExtension(childBt.name ?? string.Empty);
                    if (string.IsNullOrWhiteSpace(childBtName))
                        childBtName = $"BlendTree_{i}";

                    // 子 BlendTree class：BT_XXX（更短更直观；避免和 Clip 字段混）
                    string typeBase = SanitizeTypeName($"BT_{childBtName}");
                    string typeName = MakeUnique(typeBase, usedBtTypeNames);

                    sb.AppendLine($"{indentInnerClass}public static class {typeName}");
                    sb.AppendLine($"{indentInnerClass}{{");

                    // 子 BlendTree 内部递归输出（缩进 +1）
                    string nextIndentMember = indentMember + "    ";
                    string nextIndentInnerClass = indentInnerClass + "    ";

                    EmitBlendTreeBody(
                        sb,
                        indentMember: nextIndentMember,
                        indentInnerClass: nextIndentInnerClass,
                        stateName: stateName,
                        bt: childBt,
                        btDisplayName: childBtName,
                        exportedCount: ref exportedCount
                    );

                    sb.AppendLine($"{indentInnerClass}}}");
                    continue;
                }
                else
                {
                    // Clip / 其它 Motion：直接在当前层输出 tuple 常量
                    string motionName = TrimAnimExtension(m.name ?? string.Empty);
                    if (string.IsNullOrWhiteSpace(motionName))
                        motionName = $"Motion_{i}";

                    string fieldBase = SanitizeConstFieldName(motionName);
                    string fieldName = MakeUnique(fieldBase, usedClipFieldNames);

                    sb.AppendLine(
                        $"{indentMember}public static readonly (string stateName, string motionName) {fieldName} = " +
                        $"(\"{EscapeForCSharpString(stateName)}\", \"{EscapeForCSharpString(motionName)}\");"
                    );
                    exportedCount++;
                }
            }
        }

        private static string TrimAnimExtension(string name)
        {
            if (string.IsNullOrEmpty(name)) return string.Empty;
            if (name.EndsWith(".anim", StringComparison.OrdinalIgnoreCase))
                return name.Substring(0, name.Length - 5);
            return name;
        }

        private static string MakeUnique(string baseName, HashSet<string> used)
        {
            if (used.Add(baseName))
                return baseName;

            int n = 2;
            while (true)
            {
                string candidate = $"{baseName}_{n}";
                if (used.Add(candidate))
                    return candidate;
                n++;
            }
        }

        // ---- identifier sanitize ----

        private static string SanitizeTypeName(string raw)
        {
            string s = SanitizeIdentifierCore(raw);
            if (string.IsNullOrEmpty(s)) s = "Unnamed";
            if (char.IsDigit(s[0])) s = "_" + s;
            return s;
        }

        private static string SanitizeEnumMember(string raw)
        {
            string s = SanitizeIdentifierCore(raw);
            if (string.IsNullOrEmpty(s)) s = "Unnamed";
            if (char.IsDigit(s[0])) s = "_" + s;
            return s;
        }

        private static string SanitizeConstFieldName(string raw)
        {
            string s = SanitizeIdentifierCore(raw);
            if (string.IsNullOrEmpty(s)) s = "Unnamed";
            if (char.IsDigit(s[0])) s = "_" + s;
            return s;
        }

        private static string SanitizeIdentifierCore(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw)) return "";

            var sb = new StringBuilder(raw.Length);
            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];

                // 允许字母/数字/下划线，其它全部转成下划线
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            // 合并连续下划线
            string s = sb.ToString();
            while (s.Contains("__", StringComparison.Ordinal))
                s = s.Replace("__", "_", StringComparison.Ordinal);

            // 避免 C# 关键字（简化处理：前面加 @）
            if (IsCSharpKeyword(s))
                s = "@" + s;

            return s;
        }

        private static bool IsCSharpKeyword(string s)
        {
            // 够用的一组；需要更全可以继续补
            return s is
                "class" or "enum" or "namespace" or "public" or "private" or "protected" or "internal" or
                "static" or "const" or "string" or "int" or "float" or "bool" or "void" or
                "new" or "null" or "true" or "false" or "return" or "if" or "else" or
                "switch" or "case" or "default" or "for" or "foreach" or "while" or "do" or
                "break" or "continue";
        }

        // ---- escaping ----

        private static string EscapeForCSharpString(string s)
        {
            return s
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }

        private static string EscapeForXml(string s)
        {
            return s
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }
    }
}
